### PR TITLE
Add label_formatter callback

### PR DESCRIPTION
**Pull request by jds13**
I added a label_formatter callback to pie.rb.  For example, to substitute the "label" for the "value" in a pie chart, use this:
<pre>
   g = Gruff::Pie.new("350x180")
   g.label_formatter = Proc.new { |data_row| data_row[0] }       # Select label from [label, value, color ]
</pre>
This can be used to format numbers or substitute text.
I apologize for the whitespace changes that confuse things. This is my first github contribution.

### CODE REVIEW

**Comment by donv** [comment]
Hi @jds13 !

I am working on merging PRs.  Could you rebase this one against master and push again?

**Comment by donv** [comment]
Hi @jds13 !

I am working on merging PRs now.  Can you rebase this one against master and push again?

**Comment by jds13** [comment]
I am traveling on holiday in Germany right now - Berlin - Dresden -
Würzburg - and won't be able to do this until June 15  at the earliest. I
cannot access my office computer remotely.

I hope the delay is not a problem. My apologies.

**Comment by donv** [comment]
No problem!  Looking forward to it.

**Comment by jds13** [comment]
Superseded by #128

**Pull request closed without merging**
