### PR TITLE
Fix side bars

### PR DESCRIPTION
**Pull request by MentalPower**
During our use of this library inside of my company, we noticed (and fixed) these issues:
1. If one or more of the data columns for the side stacked bars is zero, the placement of any subsequent bars was pulled to the left.
2. Fixed the inaccurate line markers that resulted from post-processing of the label's precision from base.rb's label() function after we decided where to draw the marker.
3. If an empty string was passed as a label, this would throw an exception.
4. y_axis_increment was available, but x_axis_increment was not.

### CODE REVIEW

**Comment by joseschmidt** [comment]
So, what if i wanted labels only every x elements? Right now i'm using the line chart with many many values. To gain some nice visibility i'm using ' ' when i don't need a label, will this through an exception?

**Comment by MentalPower** [comment]
@joseschmidt, this is actually the reverse. Previously you could not use '' (empty string) as a label because the code would try and determine the size of it and freak out. You're using ' ' (single space) so your usage is not impacted by this fix. After this gets merged in, you could use '' instead to not cause the code to adjust placement decisions based on an invisible label.

**Comment by joseschmidt** [comment]
@MentalPower Aw thats awesome! sorry yes i remember now that i had to use ' ' because the empty string was throwing an error. Thanks :+1:

**Comment by donv** [comment]
Hi @MentalPower !

I would like to merge this PR, but master has moved a bit.  Can you rebase against master and push again?

**Comment by MentalPower** [comment]
Just updated, let me know if there is anything else you need.

**Comment by donv** [comment]
Hi @MentalPower !  Thanks!

Could you review the test images?  I think I see some drawing errors where the axis marker lines look off.

**Comment by Watson1978** [comment]
I believe that your issue should be solved by https://github.com/topfunky/gruff/pull/466

**Pull request closed without merging**
