### PR TITLE
Improve scatter graph

### PR DESCRIPTION
**Pull request by iox**
I needed to create a yearly activity graph with Gruff, and I encountered several limitations. Having finally achieved my purpose, I wanted to share my changes:

* Allow customising the size of the points
* Allow disabling the significant rounding when labeling the X axis
* Allow enabling vertical lines. When you have a lot of data, they can work great
* Allow using vertical labels in the X axis (and setting the label margin)
* Allow passing lambdas to format labels

I have included a test with some fake data and the corresponding PNG.

scatter_custom_label_format

### CODE REVIEW

**Comment by donv** [comment]
Hi @iox !

This looks good, and I am ready to merge, but could you look at the travis error and fix the use of Date#to_time?

We are still Ruby 1.8.7 compatible :)

**Comment by iox** [comment]
Thanks :). Sure, I'll fix it.

**Comment by iox** [comment]
Now it's green :)

**Comment by donv** [comment]
Thanks!

**Pull request merged**
