### PR TITLE
Refactor Gruff::Pie to Improve Ability to Subclass

### PR DESCRIPTION
**Pull request by h0tl33t**
I wanted to be able to tweak a few specific pieces of functionality in `Gruff::Pie` charts, but wasn't able to unless I overwrote both the `draw` and `draw_label` methods, which currently contain pretty much all the functionality.  In order to avoid a bunch of duplication when overwriting methods, I refactored `Gruff::Pie` by  breaking the `draw` and `draw_label` methods into much smaller component methods.

If I want to change a specific value, I can then simply subclass from `Gruff::Pie` in my app and re-write maybe the one or two methods that deal specifically with the logic I wanted to change.

I wanted to share the work I did here in case it might be helpful for others.  Thanks!

### CODE REVIEW

**Comment by donv** [comment]
Hi @h0tl33t !

I am working on merging PRs now.  Can you rebase this one against master and push again?

**Comment by h0tl33t** [comment]
@donv -- Done!  Thanks.

**Comment by donv** [comment]
OK, looks good.  @h0tl33t did you run the tests?  Any changes in the screen shots?

**Comment by donv** [comment]
@h0tl33t Any chance you could add a test with screenshot for subclassing the Pie chart?

**Comment by h0tl33t** [comment]
@donv - All existing tests look the same -- I can commit the pie output images if you'd like.

I added a test demonstrating how you could subclass `Gruff::Pie` -- let me know if that's what you were thinking.

**Comment by donv** [comment]
Looks good!  Thanks!

**Pull request merged**
